[package]
name = "aicad"
version = "0.1.0"
edition = "2024"
crate-type = ["cdylib", "rlib"]

[dependencies]
rustc-hash = "2.1"
pyo3 = { version= "0.28", features = ["extension-module"] }
rayon = "1"
rand = "0.10"
rand_xoshiro = "0.8"
deepsize = "0.2.0"
# need to deactivate op-fusion due to a bug in cubecl resulting in invalid memory access
#burn = { version = "~0.21", features = ["train", "ndarray", "cuda"] }
burn = { version = "~0.21", default-features = false, features = ["train", "ndarray", "cuda", "std", "autotune"] }
serde = "1.0"
log = "0.4"
pyo3-log = "0.13"
dyn-clone = ">=0.1"
indicatif = { version = "0.18", features = ["rayon"] }

[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "katex-header.html" ]
